# Generated by Django 5.1.1 on 2025-10-20 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTLT_App', '0004_accountuploadnotification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=15)),
                ('professor_name', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('student_id', models.CharField(max_length=50)),
                ('course_section_name', models.CharField(blank=True, max_length=150, null=True)),
                ('course_code', models.CharField(blank=True, max_length=50, null=True)),
                ('course_title', models.CharField(blank=True, max_length=255, null=True)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
