# Generated by Django 5.1.1 on 2025-10-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTLT_App', '0005_attendancearchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecordArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course_code', models.CharField(max_length=50)),
                ('course_section_name', models.CharField(blank=True, max_length=150, null=True)),
                ('professor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('fingerprint_data', models.BinaryField()),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='AttendanceArchive',
        ),
        migrations.AddField(
            model_name='semester',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
