# Generated by Django 5.1.1 on 2025-11-15 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTLT_App', '0006_attendancerecordarchive_delete_attendancearchive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='semester',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='school_year',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester'), ('Summer', 'Summer')], default='First Semester', max_length=50),
        ),
        migrations.AddField(
            model_name='semester',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('semester_name', 'school_year')},
        ),
    ]
