# Generated by Django 5.1.1 on 2025-11-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTLT_App', '0007_alter_semester_options_semester_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='professor_time_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Professor Time In'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='professor_time_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Professor Time Out'),
        ),
    ]
