# Generated by Django 5.1.1 on 2025-11-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTLT_App', '0008_attendancerecord_professor_time_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('LATE', 'Late'), ('Absent', 'Absent'), ('Excused', 'Excused'), ('No time-out', 'No time-out')], max_length=15, verbose_name='Status'),
        ),
    ]
